// <auto-generated />
using GuildRPG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuildRPG.Migrations
{
    [DbContext(typeof(GuildRPGContext))]
    [Migration("20250602153312_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuildRPG.Models.Mercenary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentHealth")
                        .HasColumnType("float");

                    b.Property<double>("Damage")
                        .HasColumnType("float");

                    b.Property<double>("ExperiencePoints")
                        .HasColumnType("float");

                    b.Property<double>("Gold")
                        .HasColumnType("float");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<double>("MaxHealth")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mercenary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentHealth = 100.0,
                            Damage = 15.0,
                            ExperiencePoints = 100.0,
                            Gold = 42198.0,
                            Level = 5,
                            MaxHealth = 100.0,
                            Name = "Arthur"
                        },
                        new
                        {
                            Id = 2,
                            CurrentHealth = 120.0,
                            Damage = 20.0,
                            ExperiencePoints = 100.0,
                            Gold = 42198.0,
                            Level = 7,
                            MaxHealth = 120.0,
                            Name = "Lancelot"
                        },
                        new
                        {
                            Id = 3,
                            CurrentHealth = 10000.0,
                            Damage = 1500.0,
                            ExperiencePoints = 100.0,
                            Gold = 42198.0,
                            Level = 25,
                            MaxHealth = 10000.0,
                            Name = "Paulina Heros"
                        },
                        new
                        {
                            Id = 4,
                            CurrentHealth = 100000.0,
                            Damage = 100000.0,
                            ExperiencePoints = 100.0,
                            Gold = 42198.0,
                            Level = 99,
                            MaxHealth = 100000.0,
                            Name = "Cieć Boss"
                        },
                        new
                        {
                            Id = 5,
                            CurrentHealth = 100.0,
                            Damage = 15.0,
                            ExperiencePoints = 100.0,
                            Gold = 42198.0,
                            Level = 8,
                            MaxHealth = 100.0,
                            Name = "Zwykły Maciek"
                        },
                        new
                        {
                            Id = 6,
                            CurrentHealth = 100.0,
                            Damage = 15.0,
                            ExperiencePoints = 100.0,
                            Gold = 42198.0,
                            Level = 1,
                            MaxHealth = 100.0,
                            Name = "Kasztan ze wsi"
                        },
                        new
                        {
                            Id = 7,
                            CurrentHealth = 100.0,
                            Damage = 15.0,
                            ExperiencePoints = 100.0,
                            Gold = 42198.0,
                            Level = 9,
                            MaxHealth = 100.0,
                            Name = "Dres spod żabki"
                        },
                        new
                        {
                            Id = 8,
                            CurrentHealth = 100.0,
                            Damage = 15.0,
                            ExperiencePoints = 100.0,
                            Gold = 42198.0,
                            Level = 5,
                            MaxHealth = 100.0,
                            Name = "Nie mam Więcej pomysłów"
                        });
                });

            modelBuilder.Entity("GuildRPG.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Damage")
                        .HasColumnType("float");

                    b.Property<double>("Health")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Monster");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 200.0,
                            Health = 2000.0,
                            Name = "Smokuch"
                        },
                        new
                        {
                            Id = 2,
                            Damage = 5.0,
                            Health = 100.0,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 3,
                            Damage = 100.0,
                            Health = 800.0,
                            Name = "Paulina Wiedźma"
                        },
                        new
                        {
                            Id = 4,
                            Damage = 50.0,
                            Health = 500.0,
                            Name = "Ork"
                        },
                        new
                        {
                            Id = 5,
                            Damage = 150.0,
                            Health = 1500.0,
                            Name = "Czerwony Ork"
                        },
                        new
                        {
                            Id = 6,
                            Damage = 200.0,
                            Health = 2000.0,
                            Name = "Bestia z Groty"
                        },
                        new
                        {
                            Id = 7,
                            Damage = 1.0,
                            Health = 10.0,
                            Name = "Żul Mietek"
                        },
                        new
                        {
                            Id = 8,
                            Damage = 1000.0,
                            Health = 10000.0,
                            Name = "Mamlambo"
                        },
                        new
                        {
                            Id = 9,
                            Damage = 999999.0,
                            Health = 999999.0,
                            Name = "Diabeł"
                        });
                });

            modelBuilder.Entity("GuildRPG.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Diff")
                        .HasColumnType("int");

                    b.Property<int>("EnemyId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RewardMoney")
                        .HasColumnType("float");

                    b.Property<double>("RewardXP")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.ToTable("Quest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "aaaaaaaaaaaaaaaaaaaa",
                            Diff = 5,
                            EnemyId = 1,
                            Location = "Góry Mroczne",
                            Name = "Smocza Grota",
                            RewardMoney = 0.0,
                            RewardXP = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "BBBBBBBBBBBBBBBB",
                            Diff = 3,
                            EnemyId = 2,
                            Location = "Las Cienia",
                            Name = "Goblińska Wioska",
                            RewardMoney = 0.0,
                            RewardXP = 0.0
                        });
                });

            modelBuilder.Entity("GuildRPG.Models.Quest", b =>
                {
                    b.HasOne("GuildRPG.Models.Monster", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");
                });
#pragma warning restore 612, 618
        }
    }
}
